#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FirstAid.Resource", IsApplication=true)]

namespace FirstAid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int theme_custom_background = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int theme_devicedefault_background = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int theme_firstaid_background = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int theme_material_settings_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Card1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Card2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Card3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Card4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_ = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int MaterialMenu1a = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int MaterialMenu1b = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int MaterialMenu2a = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int MaterialMenu3a = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int MaterialMenu3b = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int MaterialMenu4a = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splash = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int MaterialItem1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MaterialItem2 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int MaterialItem3 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int MaterialItem4 = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int Theme_Custom = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Theme_Custom1 = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int Theme_FirstAid = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
